### ISSUE TITLE
BUG: Multiple click on card

### ISSUE THREAD

**Issue by yustme** [slunickova/PexesoDP#1]
## Issue
It should be NOT possible to undercover more than 2 cards at one turn.

## How to replicate
Click quickly on more than 2 cards.

![peek 2019-01-27 09-22](https://user-images.githubusercontent.com/5272798/51798911-5447da80-221a-11e9-8ba1-4433eeb59bc6.gif)

## Possible solution
Change this:
https://github.com/slunickova/PexesoDP/blob/532bd6271e6005b296058e169110a5bc5152eaf6/js/app.js#L97-L99
to this
```
  } else if (selectedCards.length === 0) {
```

**Comment by slunickova** [comment]
Thanks for my first Issue!
I tried to unlock pull requests. Would you check? Want to collaborate ;)

**Comment by yustme** [comment]
Add me to collaborates ;)

**Comment by slunickova** [comment]
https://github.com/slunickova/PexesoDP/invitations 

Fakt? To musím každého jmenovitě přidat? Nemůže mi kdokoliv poslat pull request? Nějak těm nastavením pořád nerozumím O:-)

**Comment by yustme** [comment]
Musí se změnit nastavení v repozitáři. Popravdě z hlavy nevím, kde to je :confused: 

Tady je první PR (Pull Request) #2 :+1:  Pak se tam objeví tlačítko "Add your review" myslím a tam můžeš dát "approve" nebo když se ti to nebude líbit tak "request changes". Pokud mi to schválíš, tak to zamerguju do masteru a bude nová verze ! :+1:
